# Generated by Django 3.2.7 on 2021-09-05 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do cliente')),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefone')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
                ('city', models.CharField(max_length=50, verbose_name='Cidade')),
                ('grade', models.FloatField(default=5, max_length=3, verbose_name='Nota')),
                ('code', models.CharField(max_length=15, unique=True, verbose_name='CPF ou CNPJ')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Data de cadastro')),
                ('last_update', models.DateTimeField(auto_now_add=True, verbose_name='Última atualização')),
                ('business', models.CharField(choices=[('Provedor', 'Provedor'), ('Integrador', 'Integrador'), ('Cliente Final', 'Cliente Final')], max_length=50, verbose_name='Tipo de cliente')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que cadastrou')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
