# Generated by Django 3.2.6 on 2021-08-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210814_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(max_length=15, unique=True, verbose_name='CPF ou CNPJ'),
        ),
    ]
