# Generated by Django 3.2.6 on 2021-08-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20210814_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, default=5, max_digits=3, verbose_name='Nota'),
        ),
    ]
