# Generated by Django 3.2.6 on 2021-08-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_client_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='grade',
            field=models.FloatField(default=5, max_length=3, verbose_name='Nota'),
        ),
    ]
