version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
     - SECRET_KEY=samplesecret123
     - DEBUG=1
     - DB_HOST=db
     - DB_NAME=app
     - DB_USER=postgres
     - DB_PASS=secretpassword
    depends_on:
     - db

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "8080:8080"
    depends_on:
      - app

  db:
    image: postgres:13.0-alpine
    environment:
     - POSTGRES_DB=app
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=secretpassword

volumes:
  static_data:
  postgres-data: