# Generated by Django 3.2.6 on 2021-08-09 23:53

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=20, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=20, verbose_name='Sobrenome')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Nome de usuário')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='E-mail')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='Última sessão')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('is_superadmin', models.BooleanField(default=False, verbose_name='Super admin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
