# Generated by Django 3.2.6 on 2021-09-08 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_tested', models.CharField(max_length=20, verbose_name='Produto testado')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantidade testada')),
                ('test_type', models.CharField(choices=[('Usabilidade', 'Usabilidade'), ('Campo', 'Campo')], max_length=20, null=True, verbose_name='Tipo de teste')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de início')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de finalização')),
                ('technician', models.CharField(blank=True, max_length=30, verbose_name='Nome do instalador/técnico')),
                ('contract_id', models.CharField(blank=True, max_length=50, verbose_name='Código do contrato')),
                ('status', models.CharField(blank=True, choices=[('Finalizado', 'Finalizado'), ('Em andamento', 'Em andamento')], default='Em andamento', max_length=20, verbose_name='Status')),
                ('tk_grade', models.FloatField(default=5, verbose_name='Nota do conhecimento técnico')),
                ('tk_comments', models.TextField(blank=True, max_length=1000, verbose_name='Comentário sobre conhecimento técnico')),
                ('tr_grade', models.FloatField(default=5, verbose_name='Nota do tempo de resposta')),
                ('tr_comments', models.TextField(blank=True, max_length=1000, verbose_name='Comentário sobre o tempo de resposta')),
                ('fb_grade', models.FloatField(default=5, verbose_name='Nota do feedback que o cliente forneceu')),
                ('fb_comments', models.TextField(blank=True, max_length=1000, verbose_name='Comentário sobre o feedback que o cliente forneceu')),
                ('final_grade', models.FloatField(default=5, verbose_name='Nota final')),
                ('final_comments', models.TextField(blank=True, max_length=300, verbose_name='Comentários finais')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usário que criou')),
            ],
            options={
                'verbose_name': 'Teste',
                'verbose_name_plural': 'Testes',
            },
        ),
        migrations.CreateModel(
            name='TestImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='tests/images', verbose_name='Imagem')),
                ('test', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Teste')),
            ],
            options={
                'verbose_name': 'Imagens do teste',
                'verbose_name_plural': 'Imagens do teste',
            },
        ),
    ]
