# Generated by Django 3.2.7 on 2021-09-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='scenario',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Cenário de instalação'),
        ),
        migrations.AddField(
            model_name='test',
            name='ti_comments',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Comentário sobre o tempo de instalação'),
        ),
        migrations.AddField(
            model_name='test',
            name='ti_grade',
            field=models.FloatField(default=5, verbose_name='Nota do tempo de instalação'),
        ),
        migrations.AlterField(
            model_name='test',
            name='final_comments',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Comentários finais'),
        ),
    ]
