# Generated by Django 3.2.6 on 2021-08-19 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0006_auto_20210814_1420'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_tested', models.CharField(max_length=20, verbose_name='Produto testado')),
                ('start_date', models.DateField(verbose_name='Data de início')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('end_date', models.DateField(blank=True, verbose_name='Data de finalização')),
                ('technician', models.CharField(max_length=30, verbose_name='Nome do instalador/técnico')),
                ('tk_grade', models.DecimalField(blank=True, decimal_places=2, default=5, max_digits=3, verbose_name='Nota do conhecimento técnico')),
                ('tk_comments', models.CharField(blank=True, max_length=300, verbose_name='Comentário sobre conhecimento técnico')),
                ('tr_grade', models.DecimalField(blank=True, decimal_places=2, default=5, max_digits=3, verbose_name='Nota do tempo de resposta')),
                ('tr_comments', models.CharField(blank=True, max_length=300, verbose_name='Comentário sobre o tempo de resposta')),
                ('fb_grade', models.DecimalField(blank=True, decimal_places=2, default=5, max_digits=3, verbose_name='Nota do feedback que o cliente forneceu')),
                ('fb_comments', models.CharField(blank=True, max_length=300, verbose_name='Comentário sobre o feedback que o cliente forneceu')),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, default=5, max_digits=3, verbose_name='Nota final')),
                ('final_comments', models.CharField(blank=True, max_length=300, verbose_name='Comentários finais')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usário que criou')),
            ],
            options={
                'verbose_name': 'Teste',
                'verbose_name_plural': 'Testes',
            },
        ),
    ]
