# Generated by Django 3.2.7 on 2021-09-06 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='tests/images', verbose_name='Imagem')),
                ('test', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Teste')),
            ],
            options={
                'verbose_name': 'Imagens do teste',
                'verbose_name_plural': 'Imagens do teste',
            },
        ),
    ]
