# Generated by Django 3.2.6 on 2021-08-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20210819_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='contract_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código do contrato'),
        ),
        migrations.AlterField(
            model_name='test',
            name='technician',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nome do instalador/técnico'),
        ),
    ]
