# Generated by Django 3.2.6 on 2021-08-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20210821_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de finalização'),
        ),
    ]
