# Generated by Django 3.2.6 on 2021-08-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_alter_test_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='fb_grade',
            field=models.FloatField(default=5, verbose_name='Nota do feedback que o cliente forneceu'),
        ),
        migrations.AlterField(
            model_name='test',
            name='final_grade',
            field=models.FloatField(default=5, verbose_name='Nota final'),
        ),
        migrations.AlterField(
            model_name='test',
            name='tk_grade',
            field=models.FloatField(default=5, verbose_name='Nota do conhecimento técnico'),
        ),
        migrations.AlterField(
            model_name='test',
            name='tr_grade',
            field=models.FloatField(default=5, verbose_name='Nota do tempo de resposta'),
        ),
    ]
