# Generated by Django 3.2.6 on 2021-09-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_test_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='Data de início'),
        ),
    ]
