# Generated by Django 3.2.6 on 2021-09-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_alter_test_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de início'),
        ),
    ]
